# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
general:
  branches:
    only:
      - ci
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:boot-2.7.2
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - project-{{checksum "query/boot.properties" }}-{{ checksum "query/build.boot" }}
          # fallback to using the latest cache if no exact match is found
          - project-

      - run:
          command: |
            cd query
            boot show -d

      - save_cache:
          paths:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project-{{checksum "query/boot.properties" }}-{{ checksum "query/build.boot" }}
        
      # run tests!
      - run:
          command: |
            cd query
            boot coverage
            cp -R target/coverage/journal ~/coverage
      - store_artifacts:
          path: ~/coverage/